#!/bin/sh

# comment / block
#sed -i '' 's/\(^[^#]*#\ temp\-block\)$/#\1/' sup.txt

# uncomment / unblock
#sed -i '' 's/^#\(.*#\ temp\-block\)$/\1/' sup.txt

#lead='^# focus blocked sites start$'
#tail='^# focus blocked sites end$'
#sed -e "/$lead/,/$tail/{ /$lead/{p; r blocked
#        }; /$tail/p; d;}"  sup.txt
