#!/bin/sh

file='sup.txt'
lead='# focus block start'
tail='# focus block end'

trap ctrl_c INT
function ctrl_c() {
  echo "\n\nunblocking websites.."
  sudo sed -i.bkp -e "/$lead/,/$tail/d" $file
  echo "done, go play, kid"
}

echo "blocking websites.."
sudo ./block-websites
echo "blocked!"

# clear dns cache
echo "\nclearing dns"
sudo killall -HUP mDNSResponder

# start node server listening on port 80
echo "\nstarting server.."
echo "haha now you gotta work! you'll have to :)"
sudo node server.js

