#!/bin/sh

trap ctrl_c INT
function ctrl_c() {
  echo "\n\nunblocking websites.."
  echo "done, go play, kid"
}

echo "blocking websites.."
echo "blocked!"

# clear dns cache
echo "\nclearing dns"
sudo killall -HUP mDNSResponder

# start node server listening on port 80
echo "\nstarting server.."
echo "haha now you gotta work! you'll have to :)"
sudo node server.js

